version: 1.0.1.{build}
branches:
  only:
  - feature/public-xplat-netstd-appveyor
max_jobs: 1
image:
  - Visual Studio 2017
  - Ubuntu1804
configuration: Debug
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '1.0.1.0'
  assembly_version: '1.0.1.0'
  file_version: '1.0.1.0'
  package_version: '{version}'
  informational_version: '1.0.1-dev{build}'
cache:
  - src/TestTargets/bin
build:
  project: Microsoft.Diagnostics.Runtime.sln
  verbosity: minimal
before_build:
  - nuget restore